#!/usr/bin/env python3
"""Build the static GitHub Pages artifact from ``web/``."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the CD Monitor GitHub Pages site")
    parser.add_argument("--source", default="web")
    parser.add_argument("--dest", default="_site")
    parser.add_argument("--api-base", default="")
    args = parser.parse_args()
    source = Path(args.source).resolve()
    dest = Path(args.dest).resolve()
    if not (source / "index.html").is_file():
        parser.error(f"missing frontend source: {source / 'index.html'}")
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(source, dest)
    runtime_config = (
        "// Generated by scripts/build_pages.py; do not put secrets here.\n"
        "window.CD_MONITOR_CONFIG = {\n"
        f"  apiBase: {json.dumps(args.api_base.strip().rstrip('/'))},\n"
        "  accessToken: \"\",\n"
        "};\n"
    )
    # Keep the stable file for viewers with a previously cached index, but make
    # every new build refer to a fingerprinted filename.  GitHub Pages can cache
    # static assets aggressively; the fingerprint prevents a changed API origin
    # from silently reusing an earlier runtime configuration.
    (dest / "runtime-config.js").write_text(runtime_config, encoding="utf-8")
    digest = hashlib.sha256(runtime_config.encode("utf-8")).hexdigest()[:12]
    runtime_name = f"runtime-config.{digest}.js"
    (dest / runtime_name).write_text(runtime_config, encoding="utf-8")
    index = dest / "index.html"
    markup = index.read_text(encoding="utf-8")
    stable_reference = 'src="runtime-config.js"'
    if stable_reference not in markup:
        raise RuntimeError("missing runtime-config script reference in index.html")
    index.write_text(
        markup.replace(stable_reference, f'src="{runtime_name}"', 1),
        encoding="utf-8",
    )
    # GitHub Pages must not run Jekyll over the copied assets.
    (dest / ".nojekyll").write_text("", encoding="utf-8")
    print(f"Built {dest} (apiBase={args.api_base.strip().rstrip('/') or 'same-origin'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
